export const styles = {
  widget: {
    position: 'fixed' as const,
    bottom: '20px',
    right: '20px',
    width: '320px',
    height: '600px',
    backgroundColor: 'white',
    borderRadius: '16px',
    boxShadow: '0 5px 10px 0px rgba(0, 0, 0, 0.25)',
    transformOrigin: 'bottom right',
    overflow: 'hidden',
    zIndex: 1000,
    display: 'flex',
    flexDirection: 'column' as const,
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    transform: 'scale(0.8) translateY(20px)',
    opacity: 0,
    visibility: 'hidden' as const,
    pointerEvents: 'none' as const,
  },
  mobileWidget: {
    width: 'calc(100vw - 20px)',
    height: 'calc(100vh - 40px)',
    bottom: '20px',
    right: '10px',
    left: '10px',
    transformOrigin: 'bottom center',
  },
  header: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
    padding: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  headerTitle: {
    fontSize: '18px',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  content: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '20px',
  },
  loading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '200px',
    color: '#6b7280',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  spinner: {
    width: '20px',
    height: '20px',
    border: '2px solid #e5e7eb',
    borderTop: '2px solid #667eea',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  userCard: {
    backgroundColor: '#f8fafc',
    borderRadius: '12px',
    padding: '16px',
    marginBottom: '20px',
  },
  userName: {
    fontSize: '20px',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '4px',
  },
  userDetail: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
    color: '#6b7280',
    marginBottom: '8px',
  },
  postsSection: {
    marginTop: '20px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  postCard: {
    backgroundColor: 'white',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '12px',
    transition: 'transform 0.2s, box-shadow 0.2s',
  },
  postTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '8px',
    lineHeight: 1.4,
  },
  postBody: {
    fontSize: '13px',
    color: '#6b7280',
    lineHeight: 1.5,
  },
  postsError: {
    textAlign: 'center' as const,
    padding: '16px',
    backgroundColor: '#fef3cd',
    borderRadius: '8px',
    border: '1px solid #fde047',
    marginBottom: '16px',
    color: '#92400e',
  },
  retryButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    backgroundColor: '#667eea',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    outline: 'none',
    marginTop: '12px',
  },
}
